### ISSUE TITLE
Formatting Update Tracking

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1411]
This issue is to serve as an overall tracking for formatting files with `black` to ensure our Python files are `PEP8`. This will be validated using `Flake8`.

Run `isort` to standardize import format.

Individual PRs should be submitted for files. Groups of files can be submitted under a PR if it is appropriate. Each Issue/PR should be listed as part of this issue. Once completed, files should be checked off.

#### /converter
- [x] csv2hdf.py
- [x] lanl_format.py
- [x] hdflow.py
#### /util/test
- [x] generation.py
- [x] util.py
- [x] parallel_start_test.py
- [x] shutdown.py
- [x] __init__.py
- [x] context.py
#### /pydoc/_ext
- [x] ak_sphinx_extensions.py
#### /tests
- [x] index_test.py
- [x] base_test.py
- [x] conftest.py
- [x] coargsort_test.py
- [x] security_test.py
- [x] nan_test.py
- [x] compare_test.py
- [x] registration_test.py
- [x] extrema_test.py
- [x] check.py
- [x] array_view_test.py
- [x] numeric_test.py
- [x] sort_test.py
- [x] setops_test.py
- [x] message_test.py
- [x] string_test.py
- [x] groupby_test.py
- [x] join_test.py
- [x] dataframe_test.py
- [x] util_test.py
- [x] regex_test.py
- [x] pdarray_creation_test.py
- [x] read_all_tests.py
- [x] where_test.py
- [x] series_test.py
- [x] context.py
- [x] io_util_test.py
- [x] dtypes_tests.py
- [x] categorical_test.py
- [x] read_write_tests.py
- [x] logger_test.py
- [x] indexing_test.py
- [x] segarray_test.py
- [x] bitops_test.py
- [x] io_test.py
- [x] datetime_test.py
- [x] parquet_test.py
- [x] summarization_test.py
- [x] operator_tests.py
- [x] client_dtypes_test.py
- [x] client_test.py
#### /arkouda
- [x] infoclass.py
- [x] accessor.py
- [X] categorical.py
- [X] array_view.py
- [X] matcher.py
- [X] index.py
- [X] _version.py
- [X] alignment.py
- [X] util.py
- [X] dataframe.py
- [X] plotting.py
- [X] client.py
- [X] segarray.py
- [X] security.py
- [X] groupbyclass.py
- [X] series.py
- [X] sorting.py
- [X] message.py
- [X] dtypes.py
- [X] logger.py
- [X] join.py
- [X] pdarraycreation.py
- [X] pdarrayclass.py
- [X] numeric.py
- [X] pdarraysetops.py
- [X] client_dtypes.py
- [X] row.py
- [X] timeclass.py
- [X] pdarrayIO.py
- [X] io_util.py
- [X] strings.py
- [X] match.py
#### /benchmarks
- [X] setops.py
- [X] multiIO.py
- [X] aggregate.py
- [X] gather.py
- [X] segarray_setops.py
- [X] coargsort.py
- [X] argsort.py
- [X] flatten.py
- [X] str-locality.py
- [X] substring_search.py
- [X] str-groupby.py
- [X] reduce.py
- [X] dataframe.py
- [X] str-in1d.py
- [X] IO.py
- [X] str-gather.py
- [X] stream.py
- [X] setops_multiarray.py
- [X] scatter.py
- [X] in1d.py
- [X] sort-cases.py
- [X] noop.py
- [X] scan.py
- [X] run_benchmarks.py
- [X] parquetMultiIO.py
- [X] str-argsort.py
- [X] array_transfer.py
- [X] groupby.py
- [X] parquetIO.py
- [X] str-coargsort.py
- [X] array_create.py
#### /src
- [x] serverModuleGen.py

**Comment by pierce314159** [comment]
I don't think `examples` needs to be updated since it hasn't been touched in over 2 years. We can easily do that if ppl feel otherwise, but I'm down to say this is complete! Nice job everyone!
