### ISSUE TITLE
Move `SegArray` to Server

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#1570]
SegArray is currently a client side construct that keeps track of several `pdarray` objects to manage its elements. This is very similar to `ak.String` which is currently referred to as `SegString`/`SegArray` on the server. This will eventually be transitioned to `SegString` on the server entirely as it will most likely inherit functionality from the `SegArray` module. 

This issue is to serve as an overall tracking issue for the transition.

- [x] Move `SegArray` Object from Python to Chapel (#1571)
- [ ] Move/Configure all `SegArray` functionality in Chapel (#1681 & #1682)
- [x] Update naming of `SegString` (currently `SegArray`) on the server (#1574)
- [ ] Configure `SegString` to inherit from `SegArray` to utilize the shared functionality. **(EDIT: This may not be done because there are some fundamental differences between these 2 objects that could cause problems.)**

**Comment by pierce314159** [comment]
I wanted to link [this PR](https://github.com/Bears-R-Us/arkouda/pull/830) where we first added `SegString` as a standalone object in chapel (vs two pdarrays that we logically treated as related)

I'm not sure how useful it will be but the PR description should give a good reference for our Hierarchy (`CompositeSymEntry` is where this would go i'm guessing). And maybe `src/MultiTypeSymEntry.chpl` will provide an example of sorts?

**Comment by Ethan-DeBandi99** [comment]
The SegArray server side implementation has been reverted to client side only due to functionality limitations due to the server side implementation. Closing issue.
