### ISSUE TITLE
Tracking issue for Arkouda benchmarks Research and Overhaul

### ISSUE THREAD

**Issue by joshmarshall1** [Bears-R-Us/arkouda#2193]
This issue is to track the progress of issues related to the research and reworking of the arkouda benchmarks workflow and benchmark tests.

- [ ] Research best practices for benchmark testing
- [ ] Implement JSON output for streamlined result viewing in multiple formats
- [ ] Review existing benchmarks for shortcomings, coverage information, and overall integrity
