### ISSUE TITLE
Refactor tests to not be class-based

### ISSUE THREAD

**Issue by joshmarshall1** [Bears-R-Us/arkouda#2318]
Tracking issue for updating our current class-based test suite to be aligned with our new benchmarks using PyTest. This is in anticipation of creating a single configuration file that can be used by both the benchmarks and tests

- [x] Initial configuration & alignment_test.py (#2319)
- [ ] array_view_test.py (#2320)
- [ ] bigint_agg_test.py (#2339)
- [ ] bitops_test.py (#2343)
