### ISSUE TITLE
Array API Implementation Roadmap and Progress

### ISSUE THREAD

**Issue by bmcdonald3** [Bears-R-Us/arkouda#2388]
Thinking about how we should go about this implementation with @pierce314159, we came up with the following roadmap for Array API implementaiton:

## Roadmap

- [ ] #2393
    - this would be something like https://github.com/numpy/numpy/tree/main/numpy/array_api
    - goal being that we can start getting to the point where we can run against https://github.com/data-apis/array-api-tests/tree/master to check our status
- [ ] Come up with what features still need to be implemented for 1D arrays based on that API
- [ ] Start implementation of features for 1D arrays to conform to Array API
- [ ] Start implementation of multi-dimensional arrays in Arkouda to fill out the rest of the Array API
    - this could be making the current array-view code more fleshed out (seems difficult)
    - also could be adding support for real multi-dimensional arrays (seems difficult)
    - or another method to simulate multi-dimensinoal arrays that we haven't thought of yet
    - performance not important at first, just want to focus on getting something working

## Additions to Arkouda

The layout in the Arkouda repository will:
- [ ] create a new `arkouda/array_api` directory that will house the specifics for this array api
    - prevents need for modifying existing Arkouda functionality
    - conforms with what other projects (numpy, cupy, etc.) are doing to fit into the array API
- [ ] create a new `src/array_api` directory that will house the Array API code
    - prevents mixing of code
    - requires duplication of code that is already in `src/`, but keeps things separate, allowing for different functionality
    - prevents confusion regarding modular build system
