### ISSUE TITLE
Revert SegArray to Client Side Object Only

### ISSUE THREAD

**Issue by Ethan-DeBandi99** [Bears-R-Us/arkouda#2432]
Server side objects representing SegArrays were added to reduce complexity of messages sent to the server and allow for SegArrays to be accessed as single objects instead of multiple pdarrays. Initially, there were anticipated performance gains with operations, but this implementation limits expansion of functionality. Currently, the only actual performance benefit to be gained would be from reducing message count which offers minimal boosts to performance. Due to the configuration of the Symbol Table, adding code to allow SegArrays to contain SegStrings would be extremely difficult and present a lot of challenges for maintenance. 

Baseed on the findings above, we will be removing SegArraySymEntries and SegArray server objects and reverting to the configuration where SegArray is a client side construct. This will make the code more maintainable long term and aide in the ability to expand SegArray functionality. 

This change will result in updates to server side access of SegArrays because the objects will be accessed as 2 pdarrays instead of 1 object containing the pdarrays.

## TODO
Current tasks to complete for this issue broken into client and server modification.

### Client Side
- [x] Update `__init__` to take same input as `ak.SegArray.from_parts`
- [x] Update `__init__` to configure properties.
- [x] Deprecate `ak.SegArray.from_parts`
- [x] Deprecate `ak.segarray`
- [x] Add indexing code back to client
- [x] Update IO write calls to send segments and values as 2 pdarrays.
- [x] Ensure all code interacting with SegArrays does not need to be modified for the client implementation.
- [x] Revert `_compute_non_empty` to client side? This could remain by sending the components to the server.
- [x] Message Configuration Workflows Update
- [x] Update Register/Attach Code

### Server Side
- [x] Update file write processing to access `segments` and `values` as pdarrays
- [x] Update file read processing to return `segments` and `values` as pdarrays
- [x] Multi-Column Parquet Writes Update for SegArray
- [x] Remove SegArraySymEntry
- [x] Remove SegmentedArray.chpl
- [x] Remove SegmentedArray specific functionality from SegmentedMsg.chpl
- [x] Register/Attach message processing

**Comment by Ethan-DeBandi99** [comment]
## TODO
Current tasks to complete for this issue broken into client and server modification.

### Client Side
- [ ] Update `__init__` to take same input as `ak.SegArray.from_parts`
- [ ] Update `__init__` to configure properties.
- [ ] Deprecate `ak.SegArray.from_parts`
- [ ] Deprecate `ak.segarray`
- [ ] Add indexing code back to client
- [ ] Update IO write calls to send segments and values as 2 pdarrays.
- [ ] Ensure all code interacting with SegArrays does not need to be modified for the client implementation.
- [ ] Revert `_compute_non_empty` to client side? This could remain by sending the components to the server.

### Server Side
- [ ] Update file write processing to access `segments` and `values` as pdarrays
- [ ] Update file read processing to return `segments` and `values` as pdarrays
- [ ] Remove SegArraySymEntry
- [ ] Remove SegmentedArray.chpl
- [ ] Remove SegmentedArray specific functionality from SegmentedMsg.chpl

**Comment by Ethan-DeBandi99** [comment]
I have updated the issue description with specific tasking. If any additional tasks are identified while working, they will be added for tracking.
