### ISSUE TITLE
deprecate arkouda/tests folder

### ISSUE THREAD

**Issue by ajpotts** [Bears-R-Us/arkouda#3384]
Deprecate all the tests in arkouda/tests.  This involves 

1. checking each module to make sure all the tests have been copied over to PROTO_tests/tests and verify they run.  
2. Then the test file can be moved to arkouda/tests/deprecated.
3. Finally, update `pytest.ini `to remove the relevant line.

Click on the circle to the right of an item on the list below to make a new issue and assign yourself.

- [ ] [deprecate alignment_tests.py](https://github.com/Bears-R-Us/arkouda/issues/3400)
- [ ] deprecate #3387
- [ ] #3430
- [ ] #3431
- [ ] #3433
- [ ] #3432
- [ ] #3434
- [ ] #3435
- [ ] #3436
- [ ] #3437
- [ ] #3438
- [ ] [deprecate base_test.py](https://github.com/Bears-R-Us/arkouda/issues/3402)
- [ ] [deprecate bigint_agg_test.py](https://github.com/Bears-R-Us/arkouda/issues/3403)
- [ ] [deprecate bitops_test.py](https://github.com/Bears-R-Us/arkouda/issues/3405)
- [ ] [deprecate check.py](https://github.com/Bears-R-Us/arkouda/issues/3407)
- [ ] [deprecate client_dtypes_test.py](https://github.com/Bears-R-Us/arkouda/issues/3409)
- [ ] [deprecate client_test.py](https://github.com/Bears-R-Us/arkouda/issues/3411)
- [ ] [deprecate coargsort_test.py](https://github.com/Bears-R-Us/arkouda/issues/3413)
- [x] #3414
- [ ] #3439
- [ ] #3440
- [ ] deprecate #3385
- [ ] #3441
- [ ] #3442
- [ ] #3443
- [ ] #3444
- [ ] #3445
- [ ] #3446
- [ ] #3447
- [ ] #3448
- [x] #3449
- [ ] #3450
- [ ] #3451
- [ ] deprecate #3388
- [ ] #3452
- [ ] #3453
- [ ] #3454
- [ ] #3455
- [ ] #3456
- [ ] #3457
- [ ] #3458
- [ ] #3459
- [ ] #3460
- [ ] #3461
- [ ] #3462
- [ ] #3463
- [ ] #3464
- [ ] #3465
- [ ] #3466
